export const SagaActionTypes = {
  GET_ROUTES: "@@SAGA/GET_ROUTES",
  GET_ARCHITECTS: "@@SAGA/GET_ARCHITECTS",
  GET_ARCHITECTS_DETAIL: "@@SAGA/GET_ARCHITECTS_DETAIL",
  GET_BUILDINGS: "@@SAGA/GET_BUILDINGS",
  GET_BUILDING: "@@SAGA/GET_BUILDING",
  GET_APP_ABOUT: "@@SAGA/GET_APP_ABOUT",
  GET_APP_INFO: "@@SAGA/GET_APP_INFO",
};
